### ISSUE TITLE
Add weird pronounciation: Xiaomi

### ISSUE THREAD

**Issue by eggplants** [yude/weird-pronounciation#11]
* Word: Xiaomi
* Pronounciation: ザイアオマイ
* Vocalization software: VOICEVOX ずんだもん

https://voiroda.git-server.com/v/vo7463.mp3

**Comment by yude** [comment]
Added in 650fa0eadfc547f76bf09264ed8848b4c99d6726. Thank you for contribution!

**Comment by eggplants** [comment]
`Xiaomi` is duplicated in 5a70f33a30be398445f318222e111930711a9dd0.

![Screenshot_2024-10-19-13-17-15-69_64ef5fc2000c1caa954c114bb372e1d5](https://github.com/user-attachments/assets/997a3d66-be5b-40b7-b246-01b6e3b76ae6)

**Comment by yude** [comment]
I got fucked by smh wtf, duplicated Xiaomi is deleted in 78382e3b0bf8e427df628a1141ffc37ab5721a65.
