### ISSUE TITLE
Add weird pronounciation: 原神

### ISSUE THREAD

**Issue by m-tsuru** [yude/weird-pronounciation#12]
* Word: 原神
* Pronounciation: はらがみ

(If possible, please attach an wav of pronounciation. Can be generated by using speech synthesis software like VOICEVOX.)
(Please use one of the following two.)
* Vocalization software: (Software name here. e.g., VOICEVOX ずんだもん)
* Acted by: (Person's name whose uttered this word)

**Comment by yude** [comment]
Added in 768257f94bbc1c14208bd4f4a005ad8c63b9ad6c. Thank you for contribution!
