### ISSUE TITLE
Add weird pronounciation: Kubernetes

### ISSUE THREAD

**Issue by m-tsuru** [yude/weird-pronounciation#13]
* Word: Kubernetes
* Pronounciation: キューベルネッティース

(If possible, please attach an wav of pronounciation. Can be generated by using speech synthesis software like VOICEVOX.)
(Please use one of the following two.)
* Vocalization software: (Software name here. e.g., VOICEVOX ずんだもん)
* Acted by: (Person's name whose uttered this word)

**Comment by yude** [comment]
Added in 438aad92681383b98903ee11397f0a7b6655d3db. Thank you for contribution!
