### ISSUE TITLE
Add weird pronunciation: 百度

### ISSUE THREAD

**Issue by KusaReMKN** [yude/weird-pronounciation#15]
* Word: 百度
* Pronunciation: ひゃくど
* WAV file: [ひゃくどぅ.wav.zip](https://github.com/user-attachments/files/17605559/wav.zip)
* Vocalization software: VOICEVOX 四国めたん（ノーマル）

**Comment by yude** [comment]
https://ja.wikipedia.org/wiki/%E7%99%BE%E5%BA%A6%E5%8F%82%E3%82%8A

**Comment by yude** [comment]
[百度](https://dict.baidu.com/)

**Comment by yude** [comment]
Added in a9b32bf65b49f8e1e7e7731d8d0de798834b8f52. Thank you for contribution!
