### ISSUE TITLE
ページタイトルとメタタグを単語ごとにレンダリングする

### ISSUE THREAD

**Issue by siketyan** [yude/weird-pronounciation#2]
どの単語のページを共有しても同じ Embed になってしまうので，単語をタイトルに表示して Description としてよみがなを入れたりするといい感じに表示されそうです．

<img width="739" alt="image" src="https://github.com/yude/weird-pronounciation/assets/12772118/00fd56dd-07bd-4adc-9bba-8db26a3c0197">

(会社 Slack に共有してみた様子)

**Comment by yude** [comment]
976e053b3da73980a45c1f2497204128cbd9d77a で修正しました。
ありがとうございました。

**Comment by siketyan** [comment]
素早い対応ありがとうございます！
