### ISSUE TITLE
Add weird pronounciation: HIKAKIN （廃課金）

### ISSUE THREAD

**Issue by sasakulari** [yude/weird-pronounciation#3]
* Word: HIKAKIN
* Pronounciation: はいかきん

Sorry, Pronounciation sound files are unavailable.

※この Issue は特定の個人や団体を誹謗中傷を目的とするものではありません。 HIKAKIN に関する各種権利は、すべて HIKAKIN 及び UUUM 株式会社にあります。

**Comment by yude** [comment]
da830b7f8ca65837b44ad0d2e8dc5b38f5409209 で追加しました。
ありがとうございました。
