### ISSUE TITLE
Add weird pronounciation: Air

### ISSUE THREAD

**Issue by sasakulari** [yude/weird-pronounciation#4]
* Word: Air
* Pronounciation: アイルー
with @KusaReMKN

**Comment by sasakulari** [comment]
Sound Files:

[アイルー (@KusaReMKN, @sasakulari, 春日部つむぎ, ずんだもん)](https://cdn.discordapp.com/attachments/1091585413497499700/1130140430525280266/audio_o.wav)
[アイルー (@KusaReMKN, @sasakulari)](https://cdn.discordapp.com/attachments/1091585413497499700/1130140430198116372/audio_o2.wav)

**Comment by yude** [comment]
Added in 36c0f918cac61056a4de39d220eddb5d2c9878b2. Thank you for submission.
