### ISSUE TITLE
Add weird pronounciation: AWS

### ISSUE THREAD

**Issue by eggplants** [yude/weird-pronounciation#6]
* Word: AWS
* Pronounciation: アーウッス

* Vocalization software: VOICEVOX ずんだもん

https://github.com/yude/weird-pronounciation/assets/42153744/fec69952-7382-4ade-a07f-750a7aca79c2

![image](https://github.com/yude/weird-pronounciation/assets/42153744/c40acbfa-3886-4f61-90f3-c8b6986ea80f)

**Comment by yude** [comment]
Added in 7b8bedb12dc6dc981fdda56e412905b4434710d7
