### ISSUE TITLE
Add weird pronounciation: TOEIC

### ISSUE THREAD

**Issue by m-tsuru** [yude/weird-pronounciation#8]
* Word: TOEIC
* Pronounciation: ﾄｴｲｸ

(If possible, please attach an wav of pronounciation. Can be generated by using speech synthesis software like VOICEVOX.)
(Please use one of the following two.)
* Vocalization software: (Software name here. e.g., VOICEVOX ずんだもん)
* Acted by: (Person's name whose uttered this word)

**Comment by m-tsuru** [comment]
You have to add this pronounciation with 半角カタカナ

**Comment by yude** [comment]
Added in e909263fa6a21bbca85c8b29064cfcf2e31244ca. Thank you for contribution!
